project:
  type: website
  render:
    - "*.qmd"
    - "!materials/webnotes/"

website:
  title: "Business Mathematics for UiTM"
  page-footer:
    left: "This page was built with ❤️ by [kammyariff](https://ariff118.github.io/kamansor.github.io)."
  navbar:
    background: "#4d336b"
    left:
      - href: index.qmd
        text: Home
      - text: Web Notes
        menu: 
          - href: materials/01.qmd
            text: "1. Sequence"
          - href: materials/02.qmd
            text: "2. Simple Interest"
          - href: materials/03.qmd
            text: "3. Bank Discount & Promissory Notes"
          - href: materials/04.qmd
            text: "4. Compound Interest"
          - href: materials/05.qmd
            text: "5. Annuity"
          - href: materials/06.qmd
            text: "6. Trade & Cash Discount"
          - href: materials/07.qmd
            text: "7. Mathematics of Retailing"
          - href: materials/08.qmd
            text: "8. Installment Purchase"
          - href: materials/09.qmd
            text: "9. Depreciation"
          - href: materials/10.qmd
            text: "10. Income Tax (MAT402 ONLY)"
      - href: materials/videos.qmd
        text: Learning Videos
    right: 
      # - href: "https://quarto.org/"
      #   text: "Quarto Docs"
      - icon: github
        href:  https://github.com/ariff118/
      # - icon: twitter
      #   href: https://twitter.com/quarto_pub
  sidebar: 
    style: docked
    contents: 
      - section: "Webnotes"
        contents: 
          - href: materials/01.qmd
            text: "1. Sequence"
          - href: materials/02.qmd
            text: "2. Simple Interest"
          - href: materials/03.qmd
            text: "3. Bank Discount & Promissory Notes"
          - href: materials/04.qmd
            text: "4. Compound Interest"
          - href: materials/05.qmd
            text: "5. Annuity"
          - href: materials/06.qmd
            text: "6. Trade & Cash Discount"
          - href: materials/07.qmd
            text: "7. Mathematics of Retailing"
          - href: materials/08.qmd
            text: "8. Installment Purchase"
          - href: materials/09.qmd
            text: "9. Depreciation"
          - href: materials/10.qmd
            text: "10. Income Tax (MAT402 ONLY)"

format:
  html:
    theme: united
    css: styles.css
    toc: true



