---
title: "Business Mathematics for UiTM"
format: html
---

# MAT112\

## Course Information  

### Course Learning Outcomes  
At the end of the course, students should be able to:  

1. Describe basic algebra concepts in solving business mathematical problems. (C2)\
2. Determine the solutions related to business mathematical problems. (C4)\
3. Demonstrate entrepreneurial skill related to real life business mathematical problems. (A3)\

### Course Description  
The course is primarily designed to develop the mathematical knowledge needed by the students to meet the demands of business operation. It is to provide a solid coverage of the most basic and frequently occurring business situations.  

### Syllabus Content  
1. Fundamental Concepts of Mathematics  
  1.1 Review on Algebra:  
  1.2 Sequence  
  
2. Mathematical Applications in Banking and Finance  
  2.1 Simple Interest  
  2.2 Bank Discount and Promissory Notes  
  2.3 Compound Interest  
  2.4 Annuity  
  
3. Mathematical Applications In trading and retailing  
  3.1 Trade and cash discounts  
  3.2 Mark up and Mark Down  
  3.3 Instalment Purchase  
  
4. Mathematical Applications In Accounting  
  4.1 Depreciation  
  
  
### Teaching Methodologies  
  - Lectures  
  - Tutorial  

### Proposed % Marks Approved by KPP  
| Question Difficulty | Levels Range |  
|:-------------------:|:------------:|  
| C1 - C2 | 30 - 40 |  
| C3 - C4 | 60 - 70 |  

### Assessment  

:::::: {style="display: flex; "}

::: {.column width="30%"}
Continuous Assessment:
:::

::: {.column width="5%"}
\ 
<!-- an empty Div (with a whitespace), serving as
a column separator -->
:::

::: {.column width="65%"}
50.00%  

Assessment Type: **Group Project**\
Assessment Description: **Group Assignment**\
% of Total Marks: **15%**\
CLO: **3**\

Assessment Type: **Quiz**\
Assessment Description: **Quiz**\
% of Total Marks: **10%**\
CLO: **1**\

Assessment Type: **Test**\
Assessment Description: **Test**\
% of Total Marks: **25%**\
CLO: **2**\

:::  

::::::

:::::: {style="display: flex; "}

::: {.column width="30%"}
Final Assessment:
:::

::: {.column width="5%"}
\ 
<!-- an empty Div (with a whitespace), serving as
a column separator -->
:::

::: {.column width="65%"}
50.00%  
Final Examination - 50% out of 100 on End of Semester.  
Final Examination (All Chapters)  
CLO: 1, 2, 3  
Duration : 180 minutes  
:::  

::::::  

### Transferable Skills  
Demonstrate maturity of thoughts when responding to multiple inputs and contexts.  

### Recommended Text  
1. Lau Too Kya, Phang Yook Ngor and Wee Kok Kiang 2019, Business Mathematics for UiTM, 6th edition Ed., Oxford Fajar Sdn. Bhd [ISBN: 9789834729578]\

### References  

1. Jeffrey Slater, Sharon M. Wittry 2018, Math for Business and Finance: An Algebraic Approach, 2nd Ed., Mc-Graw Hill Education [ISBN: 9781260092516]\

2. Gary Clendenen, Stanley A. Salzman 2019, Business Mathematics, 14th Ed., Pearson [ISBN: 9780134697130]\

3. Raymond A. Barnett, Ziegler Michael R, Byleen Karl E, Stocker Christopher J 2018, Finite Mathematics for Business Economics, Life Sciences and Social Sciences, 14th Ed.,
Pearson [ISBN: 9780134675985]\

4. Sheela Kannan 2019, Business Mathematics and Statistics [ISBN: 9789389088083]\

5. Sreyashi Ghosh and Sujata Sinha 2019, Business Mathematics and Statistics, 1st Ed. [ISBN: 9780199476448]\

### Other References  
This module does not have other references  

## Support Materials

<!-- | Past Semester Exam Papers | Answer Scheme |   -->
<!-- |:-------------------------:|:-------------:|   -->
<!-- | [June 2019](files/support document/mat112/MAT112 June 2019.PDF) | [Answer Scheme June 2019](files/support document/mat112/MAT112 SKEMA JUNE 2019.pdf) |   -->
<!-- | [Dec 2018](files/support document/mat112/MAT112 Dec 2018.PDF) | [Answer Scheme Dec 2018](files/support document/mat112/MAT112 SKEMA DEC 2018.pdf) |   -->
<!-- | [Jan 2018](files/support document/mat112/MAT112 Jan 2018.PDF) | [Answer Scheme Jan 2018](files/support document/mat112/MAT112 SKEMA JAN 2018.pdf) |   -->


**Past Test Paper With Answers**  
[Test 2 Dec 2019](materials/files/support document/mat112/Test 2 Dec 2019.pdf)  
[Test 1 Nov 2019](materials/files/support document/mat112/Test 1 Nov 2019.pdf)  

**Workshops Questions With Answers**  
[Nov 2019 Session 1](materials/files/support document/mat112/BENGKEL MAT112 NOV 2019 SESI 1.pdf) [Answers](materials/files/support document/mat112/Answer MAT112 Workshop Nov 2019 Session 1.pdf)  

[Nov 2019 Session 2](materials/files/support document/mat112/BENGKEL MAT112 NOV 2019 SESI 2.pdf) [Answers](materials/files/support document/mat112/Answer MAT112 Workshop Nov 2019 Session 2.pdf)  

### 20224\
[Quiz - Set 1 (10%)](materials/files/assessment/20224/MAT112/QUIZ/SET 1_QUESTIONS.pdf)\
[Quiz - Set 2 (10%)](materials/files/assessment/20224/MAT112/QUIZ/SET 2_QUESTIONS.pdf)\
[Quiz - Set 3 (10%)](materials/files/assessment/20224/MAT112/QUIZ/SET 3_QUESTIONS.pdf)\
[Quiz - Set 4 (10%)](materials/files/assessment/20224/MAT112/QUIZ/SET 4_QUESTIONS.pdf)\

<details><summary>Answers</summary>
[Quiz - Set 1 (10%)](materials/files/assessment/20224/MAT112/QSET 1_ANSWERS.pdf)\
[Quiz - Set 2 (10%)](materials/files/assessment/20224/MAT112/QSET 2_ANSWERS.pdf)\
[Quiz - Set 3 (10%)](materials/files/assessment/20224/MAT112/QUIZ/SET 3_ANSWERS.pdf)\
[Quiz - Set 4 (10%)](materials/files/assessment/20224/MAT112/QSET 4_ANSWERS.pdf)\
</details>

---

# MAT402\

## Course Information\

### *Course Learning Outcomes*\ 
At the end of the course, students should be able to:\ 

1. Describe the mathematical terms and concepts encountered in business mathematics. (C2)\
2. Evaluate the mathematical problems related to business and finance. (C5)\
3. Demonstrate the leadership, autonomy and responsibility skills to solve problems related to business mathematics. (A3)\
  
### *Course Description*\  
The course is primarily designed to develop the mathematical knowledge needed by the students to meet the demands of business operation. It is to provide a solid coverage of the most basic and frequently occurring business situations.\

### *Syllabus Content*\ 

1. Sequence  
    - Introduction to sequence  
    - Arithmetic sequence  
    - Finding the nth term and the sum of the first n terms  
    - Geometric sequence  
    - Finding the nth term and the sum of the first n terms  
  
2. Simple Interest  
    - Introduction to interest  
    - Basic Islamic banking concept  
    - Comparison between conventional and Islamic banking  
    - Simple interest formula  
    - Simple amount formula  
    - Exact time and approximate time  
    - Ordinary simple interest and exact simple interest  
    - Banker’s Rule  
    - Present Value  
  
3. Bank Discount and Promissory Notes  
    - Introduction to bank discount  
    - Introduction to promissory note  
    - Simple interest rate equivalent to bank discount rate  
  
4. Compound Interest  
    - Time value of money  
    - Introduction to compound interest  
    - Important terms use in compound interest  
    - Compound interest formula  
    - Present Value  
  
5. Annuity  
    - Introduction to annuity and types of annuities  
    - Future value of ordinary annuity certain  
    - Present value of ordinary annuity certain  
    - Solving for R and n  
  
6. Installment Purchase  
    - Introduction to installment purchase  
    - Interest based on original balance  
    - Interest based on reducing balance – constant ratio formula  
    - Unpaid principal balance using Rule of 78  
  
7. Trade and Cash Discounts  
    - Introduction to trade discount  
    - Net price formula  
    - Chain discount  
    - Single discount equivalent to chain discount  
    - Cash discount  
  
8. Mathematics of Retailing  
    - Cost, selling price, profit, loss  
    - Mark up and mark down  
    - Profit and loss: Gross profit, net profit and breakeven price  
    - Trade discount & Mathematics of retailing  
  
9. Depreciation  
    - Introduction to depreciation  
    - Straight line method  
    - Declining balance method  
  
10. Personal Income Tax  
    - Introduction to Income tax  
    - Deductions allowed  
    - Taxable income  
    - Rebates  
    - Tax rate schedule  
    - Tax assessment for individual who is single  
    - Tax assessment for individual who is married – separate and combine assessment  
  
  
### *Transferable Skills*\

- Demonstrate ability to identify and articulate self skills, knowledge and understanding confidently and in a variety of contexts. -Demonstrate ability to investigate problems and provide effective solutions.  

- Demonstrate ability to analyse issues/problems from multiple angles and make suggestions.  

### *Proposed % Marks Approved by KPP*\
Question Difficulty Levels Range\

C1 - C2 (20 - 35)\
C3 - C4 (45 - 55)\
C5 - C6 (15 - 20)\

### *Course Assessment*\

Final examination – One 3-hour paper	: 50%  
Course Work (Continuous assessments) 	: 50%  
  - Test (20%): 60 Marks (2 hours, C5)  
  - Quizzes (20%): 30 Marks (1 hour, C2)  
  - Group Assignments (10%): 100 Marks (A3)  
    
    
### *Recommended Text*\ 
1. Lau Too Kya,Phang Yook Ngor,Wee Kok Kiang, Business Mathematics for UiTM, 6th, Oxford Fajar Sdn. Bhd., 2019, ISBN: 9789834279\


### *References*\
1. Gary Clendenen, Stanley A. Salzman, Business Mathematics, 14th, Pearson, 2019, ISBN: 9780134697\

2. Jeffrey Slater,Sharon M. Wittry, Math for Business and Finance: An Algebraic Approach, 2nd, Irwin/McGraw-Hill, 2019, ISBN: 9781259957581\

3. Raymond A. Barnett, Michael R. Ziegler, Karl E. Byleen, Christopher J. Stocker, Finite Mathematics for Business, Economics, Life Sciences, and Social Sciences, 14th, Pearson, 2019, ISBN: 978013467598\

4. Edward Ira Edgerton,Wallace Edgar Bartholomew, Business Mathematics: A Textbook for Schools, Wentworth Press, 2019, ISBN: 9781012954574\

5. Ian Jacques, Mathematics for Economics and Business, 9th, Pearson Education Limited, 2018, ISBN: 9781292191669

## Group Assignment: Annuity in practices\

*Submission*\
The assignment must be submitted into Google Drive Folder (will be given by the instructors) before end of week 8. Failing to comply with the deadline given will result in deduction of marks.\

*Preparation*\
In your lessons on Annuity, you learned the meaning of annuity, types, and the formulae of calculating annuities.\
In this assignment, you are required to make a short video (3 minutes) on how annuities are practiced in real life.\
You are encouraged to do research using Internet resources.\

*Grading*\
Your  assignment will be graded using the **Video Presentation (80%)** and **Peer Evaluation (20%)** Rubrics.\
Please review and keep it in mind as you prepare your presentation, each component is weighted as follows:\

**20% Introduction**\
Introduction is interesting and addressed audience well.\

**30% Content**\
Content is organized systematically, accurately, relevantly and completely.\ 

**15% Effective Audio Visual**\
Visual aids are well usage in order to make presentation more interesting and meaningful.\

**15% Time Management**\
The presentation is able to start and complete within the time frame (3 minutes).\

## Assessment Evidence {.tabset}  

### 20202  
[Quiz 1 (2%)](materials/files/assessment/QUIZ 1 MAT112.docx)  
[Test 1 (10%)](materials/files/assessment/Test 1 MAT402 May 2020.docx)

### 20222  
[Quiz (20%)](materials/files/assessment/20222/MAT402/quiz_questions.pdf)\
[Test (20%)](materials/files/assessment/20222/MAT402/test_questions.pdf)\

### 20224  
[Quiz (20%)](materials/files/assessment/20224/MAT402/quiz_questions.pdf)\

