---
title: "Review of Algebra"
format: html
---
  
## Fractions\

::: callout-definition
A fraction is a numerical value that can be described as one value $a$ divided by another value $b$ such that $a$ and $b$ are both integer and $b\ne0$.

$$
\frac{a}{b} \ and\  b\ne0 \\
\frac{Numerator}{Denominator}
$$
:::
  
The denominator indicate the number of parts being split. The numerator shows how many parts are counted. For instance, a fraction $\frac{5}{8}$ shows that the whole was split into 8 parts, and 5 parts are counted for.\

A **mixed number** is a number that combined a whole number and a fraction. Foe example, $5\frac{2}{3}$.\

A **proper fraction** is a number such that the numerator is less than the denominator. For example, $\frac{3}{7}$\

An **improper fraction** is a number such that the numerator is greater than the denominator. For example, $\frac{9}{5}$\

## Decimals\

::: callout-definition
A decimal is a fraction written in a special form. A decimal is a number that consists of a whole and a fractional part. Decimals are the numbers, which consist of two parts namely, a whole number part and a fractional part separated by a decimal point. The word "Decimal" really means "based on 10" (From Latin decima: a tenth part). Thus, a decimal is a number expressed using a system of counting based on the number ten: Three-fifths expressed as a decimal is 0.6.  

$$
\frac{3}{5}\ =\ \frac{6}{10}\ =\ 0.6
$$
:::

To change from a fraction to a decimal value, just simply make a long division the numerator value to the denominator value.\

To change the decimal value to fraction, just moves the decimal points to the right to make it a whoe number and divide by a numerator 10 to the power of number of digits moves to the right. For example, $0.25\ =\ \frac{25}{100}\ =\ \frac{1}{4}$, after simplification.\

## Percents\

::: callout-definition
**Percentages** are expressed as the number of parts in every 100 such that it is a fraction with denominator value of 100. In other words, a percentage is a number or ratio as a fraction of 100. It is normally written with a symbol "%".
:::

To change a fraction or decimal to a percent, simply multiply the number with 100%. For example, $0.235\ \times\ 100\%\ =\ 23.5%$\

## Linear Equation\

1. A linear equation in one unknown is an equation in which the only exponent on the
unknown is 1.\
2. The general form of a basic linear equation is $ax + b = c$\
3. Solving linear equations is an important and fundamental skill in algebra.\
4. The goal is to write the equation in the form variable = constant.\
5. The solution to an equation is the set of all values that check in the equation.\

### Examples\

1. $5y − 8 = 3y + 12$\

::: {.callout-note collapse="true"}

**Answer**\
$$
\begin{align}
5y-3y&=12+8 \\
2y&=20 \\
y&=\frac{20}{2} \\
y&=10
\end{align}
$$

:::

2. $1.2x + 4.3 = 2.1 − x$\

::: {.callout-note collapse="true"}

**Answer**\
$$
\begin{align}
1.2x+x&=2.1-4.3 \\
2.2x&=-2.2 \\
x&=\frac{-2.2}{2.2} \\
x&=-1
\end{align}
$$

:::

